[package]
name = "trigger_node"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
serde = {version = "1.0.203", features = ["derive"]}
serde_json = "1.0.118"
anyhow = "1.0.86"