[package]
name = "core"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
wasmtime = { version = "22.0.0", features = ["component-model"] }
wasmtime-wasi = "22.0.0"
serde = {version = "1.0.203", features = ["derive"]}
serde_json = "1.0.118"
actix-web = "4"
